[workspace]
members = [
    "polynomial",
    "univariate-polynomial-iop-zerotest",
    "zk-plonky2-permutation-circuit"
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
