[workspace]
members = [
    "polynomial",
    "univariate-polynomial-iop-zerotest",
    "halo2-trials",
    "shamir-secret-sharing"
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
