[package]
edition = "2021"
name = "schnorr-discrete-log-proof-of-knowledge"
version = "0.1.0"

[dependencies]
ark-bls12-381 = { workspace = true }
ark-crypto-primitives = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-std = { workspace = true }
